### ISSUE TITLE
Erstellung eines Datenbank Prototyps

### ISSUE THREAD

**Issue by FinnAmini** [SmartCity-2022/Service-Bildungsportal#1]
Erste Umsetzung der Datenbanktabellen und deren Abhängigkeiten

**Comment by Hueppy** [comment]
Mit #7 wurde auch dieses Issue gelöst. Das Backend generiert automatisch die Tabellen in der Datenbank beim Start, wenn diese noch nicht existieren.

Daher schließe ich dieses Issue.
