### ISSUE TITLE
Kommunikation in das Backend fehlerhaft:

### ISSUE THREAD

**Issue by fwatermann** [SmartCity-2022/Service-Bildungsportal#39]
Das Frontend versucht das Backend unter `http://localhost/institution` zu erreichen.

Gibt es eine Möglichkeit im Frontend via ENV oder Config die URL anzugeben?

**Comment by Hueppy** [comment]
Die Umgebungsvariablen sind jetzt mit #40 in der README dokumentiert. Dadurch sollte sich dieses Problem gelöst haben.
